# Generated by Django 3.0.6 on 2020-05-18 04:10

import blog.images
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Идентификатор')),
                ('img', models.ImageField(upload_to=blog.images.upload_to, verbose_name='Изображение')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
                'ordering': ['-date_pub'],
            },
        ),
    ]
